const express = require('express');

const router = express.Router();

const exampleResources = require('./exampleResources.router');
const products = require('./products.router');
const categories = require('./categories.router');
const platforms = require('./platforms.router');
const countries = require('./countries.router');
const areas = require('./areas.router');
const cities = require('./cities.router');
const users = require('./users.router');
const favorites = require('./favorites.router');
const ratings = require('./ratings.router');
const stripe = require('./stripe.router');
const comments = require('./comments.router');
const cloudinary = require('./cloudinary.router');
const keywords = require('./keywords.router');
const tags = require('./tags.router');
const highlights = require('./highlights.router');
const userTypes = require('./userTypes.router');
const occasions = require('./occasions.router');
const useCases = require('./useCases.router');
const findAppleIdByUrl = require('./findAppleIdByUrl.router');
const sitemaps = require('./sitemaps.router');
const feeds = require('./feeds.router');
const brands = require('./brands.router');
const merchants = require('./merchants.router');

router.use('/exampleResources', exampleResources);
router.use('/products', products);
router.use('/categories', categories);
router.use('/platforms', platforms);
router.use('/countries', countries);
router.use('/areas', areas);
router.use('/cities', cities);
router.use('/users', users);
router.use('/favorites', favorites);
router.use('/ratings', ratings);
router.use('/stripe', stripe);
router.use('/cloudinary', cloudinary);
router.use('/comments', comments);
router.use('/keywords', keywords);
router.use('/tags', tags);
router.use('/highlights', highlights);
router.use('/userTypes', userTypes);
router.use('/occasions', occasions);
router.use('/useCases', useCases);
router.use('/findAppleIdByUrl', findAppleIdByUrl);
router.use('/sitemaps', sitemaps);
router.use('/feeds', feeds);
router.use('/brands', brands);
router.use('/merchants', merchants);

module.exports = router;
